//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int activityID { get; set; }
        public string activityName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string location { get; set; }
        public string ootd { get; set; }
        public byte[] createdAt { get; set; }
    }
}
